// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6J6PS1Y9GVhzdiI4ZnH8Z-V8heEAcofM',
    appId: '1:670833927075:web:91cacc4589da4317cc3016',
    messagingSenderId: '670833927075',
    projectId: 'my-logo-maker-5f336',
    authDomain: 'my-logo-maker-5f336.firebaseapp.com',
    storageBucket: 'my-logo-maker-5f336.firebasestorage.app',
    measurementId: 'G-MSNNJ115LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLqfAQeUsjw-m6aq9pEPIZlX04uyGr0Ro',
    appId: '1:670833927075:android:a3ae9bb1940d845dcc3016',
    messagingSenderId: '670833927075',
    projectId: 'my-logo-maker-5f336',
    storageBucket: 'my-logo-maker-5f336.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDellg43GCPOUqfyyDl3v9v1qjetMKz_tc',
    appId: '1:670833927075:ios:b5b43fa5d3295ad9cc3016',
    messagingSenderId: '670833927075',
    projectId: 'my-logo-maker-5f336',
    storageBucket: 'my-logo-maker-5f336.firebasestorage.app',
    iosBundleId: 'com.carlanda.user.app',
  );
}
